# Generated by Django 5.0.6 on 2024-06-24 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='Ed_and_work',
            new_name='ed_and_work',
        ),
    ]
