# Generated by Django 5.0.6 on 2024-06-24 14:53

import adminPanel.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0002_rename_ed_and_work_menu_ed_and_work'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ed_and_work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=adminPanel.models.current_year, verbose_name='Год')),
                ('desc', models.TextField()),
                ('diplom_img', models.ImageField(upload_to='Ed_and_work_img')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
