# Generated by Django 5.0.6 on 2024-06-26 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0004_alter_ed_and_work_diplom_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='slogan',
            field=models.TextField(blank=True, null=True),
        ),
    ]
