# Generated by Django 5.0.6 on 2024-06-26 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0006_case'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='feedbackes',
            new_name='feedbacks',
        ),
        migrations.AlterField(
            model_name='case',
            name='post',
            field=models.TextField(),
        ),
    ]
